#9 updated opencv version and cross compiled at new version
FHOOEAIST/aistcv pull request #10
Opened 2021-09-21 07:45 UTC by 2er0

Closes #9 

* Cross-build on Linux in Docker with no conflicts at OpenCV version 4.5.3
* Check if the JAR produced by the Linux cross-build is needed otherwise, drop it with the Windows build

2021-09-27 07:12 UTC, pointan approved these changes
Works on jenkins, so fine for me.

2021-09-27 13:40 UTC, pointan requested changes
![grafik](https://user-images.githubusercontent.com/7925259/134919902-a9c5757b-a728-4be6-b509-f23f61fa35d1.png)

Ignore my last comment, it is not working on the jenkins.

2021-09-28 06:06 UTC, pointan approved these changes
Ignore my last comment again, works on windows build agent.

2021-09-28 06:07 UTC, cpraschl approved these changes

2021-09-28 06:08 UTC, merged